### ISSUE TITLE
PuTTY-CAC with multiple CACs behaves erratically

### ISSUE THREAD

**Issue by risacher** [risacher/putty-cac#1]
[issue copied over from Forge.mil]

PuTTY-CAC behaves erratically when multiple readers and cards are present in my machine.  Presently I have 3 card readers.  In one I have my regular DoD CAC.  In another I'm using an alternate token which contains one certificate.  The third reader is empty.  I am using ActivClient middleware (acpkcs211.dll).  Basically what happens is in the pkcs11 configuration the Token labels show multiple cards.  The number next to the card seems to randomly jump around after I've clicked the dropdown more than once.  It also doesn't show anything under Certificate label.  If I manually input both the correct Token and Certificate it still doesn't work.

**Comment by NoMoreFood** [comment]
@dpksfnt I've been cleaning up old issues.   Is there anything that still needs to be worked for this issue?

**Comment by NoMoreFood** [comment]
I have tested the new PKCS #11 code with ActivClient and it seems to work fine.  Instead of depending on labels, the new code looks up the public key based on the public key modulus which are common between the certificate and the public key object.  It then uses the ID in the public key object to find the private key object.
