### ISSUE TITLE
command-line way of extracting ssh-keystring

### ISSUE THREAD

**Issue by risacher** [risacher/putty-cac#6]
users have requested a command-line tool for extracting the ssh-keystring.

**Comment by jbjonesjr** [comment]
@markhorka **OLD THREAD REVIVAL ALERT**
I use pkcs15-tool as guidance for this:
It supports:
--list-public-keys : lists all the keys in a text based way, providing basic details
--read-public-key <arg> : displays the complete public key for the arg/option passed in.  you can see the different options via list.
--rest-ssh-ley <arg> : instead of listing the key, list the "ssh-compatible" version of the public key

See [MAN Page](http://linux.die.net/man/1/pkcs15-tool) for additional details.

**Comment by NoMoreFood** [comment]
Cleaning up - I don't think that's a high enough demand to keep this around.
